version: 2


# For generic test we create .yml file and run: dbt test
# For generic test below test working fine
# We can mention the documentation configuration also to generate the document: dbt docs

models:
  - name: employee_raw
    description: "employee_raw check"
    columns:
      - name: EMPLOYEE_ID
        description: "check null value"
        tests:
          - not_null
              # config: 
              #   where: "last_name in ("Doe","Smith","Johnson")
              #   severity: error
              #   error_if: ">5"
              #   warn_if: ">3"
          - unique 

  - name: orders_raw
    description: "check orders_raw"
    columns:
      - name: ORDER_ID
        description: "check unique value"
        tests:
          - unique

  - name: products_raw
    description: "check products"
    columns:
      - name: PRODUCT_NAME
        description: "check all product"
        tests:
          - accepted_values:
              values: ['Laptop', 'Bookshelf', 'laptop', 'Smartphone']

          # -relationship:
          #   to:
          #   field:    